AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'emv-qr.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'lib/emv_qr/schema.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Style/StringLiterals:
  EnforcedStyle: double_quotes
